# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

files_with_version_number = {
    './.version' => ['{x}'],
    './PurchasesHybridCommon.podspec' => ['s.version          = "{x}"'],
    './PurchasesHybridCommonUI.podspec' => ['s.version          = "{x}"'],
    './android/gradle.properties' => ['VERSION_NAME={x}'],
    './typescript/package.json' => ['"version": "{x}"'],
    './purchases-js-hybrid-mappings/package.json' => ['"version": "{x}"'],
    './ios/PurchasesHybridCommon/PurchasesHybridCommon/Constants.swift' => [' hybridCommonVersion = "{x}"']
}
PLIST_VERSION_PATTERNS = ["<key>CFBundleShortVersionString</key>\n\t<string>{x}</string>",]
files_with_version_number_without_prerelease_modifiers = {
    './ios/PurchasesHybridCommon/Info.plist' => PLIST_VERSION_PATTERNS,
    './ios/PurchasesHybridCommon/PurchasesHybridCommonTests/Info.plist' => PLIST_VERSION_PATTERNS,
}
POD_VERSION_PATTERNS = ['\'RevenueCat\', \'{x}\'', '\'RevenueCatUI\', \'{x}\'']
SPM_VERSION_PATTERNS = ['.package(url: "https://github.com/RevenueCat/purchases-ios-spm", exact: "{x}"),']
SPM_RESOLVED_VERSION_PATTERNS = ['"version" : "{x}"']
files_to_update_ios_dependency = {
    'PurchasesHybridCommon.podspec' => POD_VERSION_PATTERNS,
    'PurchasesHybridCommonUI.podspec' => POD_VERSION_PATTERNS,
    'ios/PurchasesHybridCommon/Podfile' => POD_VERSION_PATTERNS,
    'DEVELOPMENT.md' => POD_VERSION_PATTERNS,
    'Package.swift' => SPM_VERSION_PATTERNS,
    'Package.resolved' => SPM_RESOLVED_VERSION_PATTERNS,
}

files_to_update_android_dependency = {
    'android/gradle/libs.versions.toml' => ['purchases = "{x}"']
}
files_to_update_js_dependency = {
    'purchases-js-hybrid-mappings/package.json' => ['"@revenuecat/purchases-js": "{x}"']
}
repo_name = 'purchases-hybrid-common'
changelog_latest_path = './CHANGELOG.latest.md'
changelog_path = './CHANGELOG.md'

before_all do
  setup_circle_ci
  update_fastlane
end

desc "Bump version, edit changelog, and create pull request"
lane :bump do |options|
  bump_version_update_changelog_create_pr(
    current_version: current_version_number,
    changelog_latest_path: changelog_latest_path,
    changelog_path: changelog_path,
    files_to_update: files_with_version_number,
    files_to_update_without_prerelease_modifiers: files_with_version_number_without_prerelease_modifiers,
    repo_name: repo_name,
    github_rate_limit: options[:github_rate_limit],
    editor: options[:editor],
    next_version: options[:next_version],
    automatic_release: options[:automatic_release],
    is_prerelease: options[:is_prerelease]
  )
end

desc "Automatically bumps version, edit changelog, and create pull request"
lane :automatic_bump do |options|
  next_version, type_of_bump = determine_next_version_using_labels(
    repo_name: repo_name,
    github_rate_limit: options[:github_rate_limit]
  )
  options[:next_version] = next_version
  options[:automatic_release] = true
  if type_of_bump == :skip
    UI.message('Skipping automatic bump since the next version doesn\'t include public facing changes')
    next
  end

  bump(options)
end

desc "Make GitHub release for current version"
lane :github_release_current do |options|
  version_number = current_version_number
  github_release(version: version_number)
end

desc "Make GitHub release for specific version"
lane :github_release do |options|
  create_github_release(
    version: options[:version],
    repo_name: repo_name,
    github_api_token: ENV["GITHUB_TOKEN"],
    changelog_latest_path: changelog_latest_path
  )
end

desc "Trigger update dependencies to latest GitHub releases"
lane :trigger_update_dependencies do
    trigger_action(action: "dependency-update")
end

desc "Trigger bump"
lane :trigger_bump do
    trigger_action(action: "bump")
end

desc "Check typescript library API changes"
lane :check_typescript_api_changes do
  update_typescript_api_report
  sh("git diff --exit-code ../typescript/api-report/**")
end

desc "Update typescript library API report"
lane :update_typescript_api_report do
  Dir.chdir(File.expand_path('typescript', get_root_folder)) do
    sh("yarn && yarn build && yarn extract-api")
  end
end

desc "Update dependencies to latest GitHub releases and opens a PR"
lane :open_pr_upgrading_dependencies do |options|
  ensure_git_status_clean

  dry_run = options[:dry_run]

  current_ios_version = parse_previous_ios_native_version
  current_android_version = parse_previous_android_native_version
  current_js_version = parse_previous_js_version

  new_versions = update_native_dependencies_to_latest
  new_ios_version = new_versions[:new_ios_version]
  new_android_version = new_versions[:new_android_version]
  new_js_version = new_versions[:new_js_version]

  type_of_bump_ios = detect_bump_type(current_ios_version, new_ios_version)
  type_of_bump_android = detect_bump_type(current_android_version, new_android_version)
  type_of_bump_js = detect_bump_type(current_js_version, new_js_version)

  repo_status = sh("git status --porcelain")

  repo_clean = repo_status.empty?

  if repo_clean
    UI.success('Git status is clean, nothing to update! 💪')
    next
  end


  if dry_run
    UI.message("ℹ️  Nothing more to do since dry_run: true.")
    if type_of_bump_ios != :none
      UI.message("ℹ️  New iOS dependency version is #{new_ios_version}")
    end
    if type_of_bump_android != :none
      UI.message("ℹ️  New Android dependency version is #{new_android_version}")
    end
    if type_of_bump_js != :none
      UI.message("ℹ️  New JS dependency version is #{new_js_version}")
    end
    reset_git_repo
  else
    branch_ios = ""
    branch_android = ""
    branch_js = ""
    message_ios = ""
    message_android = ""
    message_js = ""

    if type_of_bump_ios != :none
      branch_ios = "-ios-#{new_ios_version}"
      message_ios = "iOS #{current_ios_version} => #{new_ios_version} "
    end
    if type_of_bump_android != :none
      branch_android = "-android-#{new_android_version}"
      message_android = "Android #{current_android_version} => #{new_android_version} "
    end
    if type_of_bump_js != :none
      branch_js = "-js-#{new_js_version}"
      message_js = "JS #{current_js_version} => #{new_js_version} "
    end

    branch = "update#{branch_ios}#{branch_android}#{branch_js}"

    sh("git stash")
    sh("git checkout -b #{branch} origin/main")
    sh("git stash pop")

    UI.success("Git switched to branch `#{branch}, all good! 💪")

    sh("git commit -am \"Upgrades versions\"")

    push_to_git_remote(
      set_upstream: true,
      remote_branch: branch
    )

    message = "[AUTOMATIC] #{message_ios}#{message_android}#{message_js}".strip

    labels = ["pr:dependencies"]
    if type_of_bump_ios == :minor || type_of_bump_android == :minor || type_of_bump_js == :minor
      labels << "pr:force_minor"
    end

    create_pull_request(
      api_token: ENV["GITHUB_TOKEN"],
      repo: "RevenueCat/#{repo_name}",
      title: message,
      head: "#{branch}",
      base: "main",
      body: message,
      labels: labels
    )
  end
end

desc "Update dependencies to latest GitHub releases"
lane :update_native_dependencies_to_latest do |options|
  current_ios_version = parse_previous_ios_native_version
  latest_ios_release = get_latest_github_release_within_same_major(repo_name: "purchases-ios", current_version: current_ios_version)

  current_android_version = parse_previous_android_native_version
  latest_android_release = get_latest_github_release_within_same_major(repo_name: "purchases-android", current_version: current_android_version)

  current_js_version = parse_previous_js_version
  latest_js_release = get_latest_github_release_within_same_major(repo_name: "purchases-js", current_version: current_js_version)

  update_ios_native_version(new_version: latest_ios_release, current_version: current_ios_version)
  update_android_native_version(new_version: latest_android_release, current_version: current_android_version)
  update_js_native_version(new_version: latest_js_release, current_version: current_js_version)
  run_pod_install

  new_versions = {
    new_ios_version: latest_ios_release,
    new_android_version: latest_android_release,
    new_js_version: latest_js_release
  }
  new_versions
end

desc "Tag current branch with current version number"
lane :tag_current_branch do |options|
  version_number = current_version_number
  check_no_git_tag_exists(version_number)

  add_git_tag(tag: version_number)
  push_git_tags(tag: version_number)
end

private_lane :trigger_action do |options|
    require 'rest-client'

    # Prompt branch
    default_branch = git_branch
    branch = UI.input("Branch (defaults to #{default_branch}): ")
    branch = default_branch if branch == ""

    # Get CircleCI token
    circle_token = ENV["CIRCLE_TOKEN"]
    UI.user_error! "Please set the CIRCLE_TOKEN environment variable" unless circle_token

    # Make request
    headers = {"Circle-Token": circle_token, "Content-Type": "application/json", "Accept": "application/json"}
    data = {parameters: {:action => options[:action]}, branch: branch}
    url = "https://circleci.com/api/v2/project/github/RevenueCat/#{repo_name}/pipeline"

    resp = RestClient.post url, data.to_json, headers

    # Print workflow url
    number = JSON.parse(resp.body)["number"]
    workflow_url = "https://app.circleci.com/pipelines/github/RevenueCat/#{repo_name}/#{number}"

    UI.important "Workflow: #{workflow_url}"
end

desc "Update purchases-ios dependency version"
private_lane :update_ios_native_version do |options|
  new_version_number = options[:new_version]
  previous_version_number = options[:current_version]

  update_native_version(
    platform_name: "iOS",
    new_version_number: new_version_number,
    previous_version_number: previous_version_number,
    files_to_update: files_to_update_ios_dependency
  )

  # Updating the commit hash in Package.resolved.
  ios_spm_repository = "https://github.com/RevenueCat/purchases-ios-spm"
  previous_commit_hash = get_commit_hash_for_tag(ios_spm_repository, previous_version_number)
  new_commit_hash = get_commit_hash_for_tag(ios_spm_repository, new_version_number)
  replace_text_in_files(
    previous_text: previous_commit_hash,
    new_text: new_commit_hash,
    paths_of_files_to_update: ["Package.resolved"]
  )
end

desc "Update purchases-android dependency version"
private_lane :update_android_native_version do |options|
  new_version_number = options[:new_version]
  previous_version_number = options[:current_version]

  update_native_version(
    platform_name: "Android",
    new_version_number: new_version_number,
    previous_version_number: previous_version_number,
    files_to_update: files_to_update_android_dependency
  )
end

desc "Update purchases-js dependency version"
private_lane :update_js_native_version do |options|
  new_version_number = options[:new_version]
  previous_version_number = options[:current_version]

  update_native_version(
    platform_name: "JS",
    new_version_number: new_version_number,
    previous_version_number: previous_version_number,
    files_to_update: files_to_update_js_dependency
  )
end

desc "Update purchases-android dependency version"
private_lane :update_native_version do |options|
  platform_name = options[:platform_name]

  dry_run = options[:dry_run]
  if options[:new_version_number]
    new_version_number = options[:new_version_number]
  else
    UI.user_error!("Missing `version` argument")
  end

  previous_version_number = options[:previous_version_number]

  if previous_version_number == new_version_number
    UI.message("ℹ️  #{platform_name} is already in its latest version: #{previous_version_number}")
    next previous_version_number
  end

  UI.message("ℹ️  Updating #{platform_name} from #{previous_version_number} to #{new_version_number}")
  files_to_update = options[:files_to_update]

  if dry_run
    UI.message("ℹ️  Nothing more to do, dry_run: true")
  else
    replace_version_number(
        current_version: previous_version_number,
        new_version_number: new_version_number,
        files_to_update: files_to_update
    )
  end
  new_version_number
end

desc "Run pod install"
lane :run_pod_install do |options|
  Dir.chdir(File.expand_path('ios/PurchasesHybridCommon', get_root_folder)) do
    sh("pod install --repo-update")
  end
end

desc "Run automatic bump in other repos"
lane :bump_hybrid_dependencies do |options|
  version_number_for_bump = current_version_number
  repo_name = options[:repo_name]

  UI.message("Triggering pipeline to bump #{repo_name} dependency to #{version_number_for_bump}")

  require 'net/http'
  require 'uri'
  require 'json'

  uri = URI.parse("https://circleci.com/api/v2/project/github/RevenueCat/#{repo_name}/pipeline")
  request = Net::HTTP::Post.new(uri)
  request.basic_auth(ENV['CIRCLECI_TOKEN'], "")
  request.content_type = "application/json"
  request.body = JSON.dump({
    "branch" => "main",
    "parameters" => {
      "action" => "upgrade-hybrid-common",
      "version" => "#{version_number_for_bump}",
      "automatic" => true
    }
  })

  req_options = {
    use_ssl: uri.scheme == "https",
  }

  response = Net::HTTP.start(uri.hostname, uri.port, req_options) do |http|
    http.request(request)
  end

  if response.code != "201"
    error_body = JSON.parse(response.body)
    error_message = error_body["message"]
    UI.error("Error triggering the pipeline.")
    UI.error("Response code: #{response.code}")
    UI.error("Error message: #{error_message}")
  end
end

platform :ios do
  desc "Release PurchasesHybridCommon to CocoaPods"
  lane :push_pod_PHC do |options|
    pod_push_with_error_handling(path: "PurchasesHybridCommon.podspec", synchronous: true)
  end

  desc "Release PurchasesHybridCommonUI to CocoaPods"
  lane :push_pod_PHCUI do |options|
    pod_push_with_error_handling(path: "PurchasesHybridCommonUI.podspec", synchronous: true)
  end

  desc "Lint Podspec"
  lane :pod_lint do |options|
    check_pods
  end

  desc "replace API KEY for integration tests"
  lane :replace_api_key_integration_tests do
    folder = './ios/PurchasesHybridCommon/PurchasesHybridCommonIntegrationTests/'

    replace_text_in_files(
      previous_text: "REVENUECAT_API_KEY",
      new_text: ENV["REVENUECAT_API_KEY"],
      paths_of_files_to_update: ["#{folder}/Constants.swift"]
    )
    replace_text_in_files(
      previous_text: "REVENUECAT_PROXY_URL",
      new_text: ENV["REVENUECAT_PROXY_URL"].to_s,
      paths_of_files_to_update: ["#{folder}/Constants.swift"],
      allow_empty: true
    )
  end
end

platform :android do
  desc "Upload and close a release"
  lane :deploy do |options|
    version = current_version_number
    gradleProperties = {
      "signing.keyId" => ENV['GPG_SIGNING_KEY_ID'],
      "signing.password" => ENV['GPG_SIGNING_KEY_PW'],
      "signing.secretKeyRingFile" => "#{File.expand_path('android', get_root_folder)}/secring.gpg",
      "mavenCentralUsername" => ENV['MAVEN_CENTRAL_PORTAL_USERNAME'],
      "mavenCentralPassword" => ENV['MAVEN_CENTRAL_PORTAL_PASSWORD'],
      "RELEASE_SIGNING_ENABLED" => true
    }
    UI.verbose("Deploying #{version}")

    gradle(
      tasks: [
        "publish --no-daemon --no-parallel"
      ],
      properties: gradleProperties,
      project_dir: 'android'
    )

    UI.verbose("Deploying bc7 version of libraries")
    gradleProperties["ANDROID_VARIANT_TO_PUBLISH"] = "bc7Release"

    # Publish hybridcommon with -bc7 suffix
    gradle(
      tasks: [
        ":hybridcommon:publish --no-daemon --no-parallel"
      ],
      properties: gradleProperties.merge({"POM_ARTIFACT_ID" => "purchases-hybrid-common-bc7"}),
      project_dir: 'android'
    )

    # Publish hybridcommon-ui with -bc7 suffix
    gradle(
      tasks: [
        ":hybridcommon-ui:publish --no-daemon --no-parallel"
      ],
      properties: gradleProperties.merge({"POM_ARTIFACT_ID" => "purchases-hybrid-common-ui-bc7"}),
      project_dir: 'android'
    )
  end
end

platform :typescript do
  desc "Deploy npm package to npm.js"
  lane :deploy do |options|
    build_and_publish_npm_package("typescript")
  end

  desc "Deploy typescript interfaces ESNext NPM package"
  lane :deploy_esm do |options|
    make_typescript_package_esm
    build_and_publish_npm_package("typescript")
  end
end

platform :web do
  desc "Run tests for purchases-js-hybrid-mappings"
  lane :test_js_mappings do |options|
    Dir.chdir(File.expand_path('purchases-js-hybrid-mappings', get_root_folder)) do
      sh("yarn && yarn test")
    end
  end

  desc "Run API tests for purchases-js-hybrid-mappings"
  lane :test_js_mappings_api do |options|
    Dir.chdir(File.expand_path('purchases-js-hybrid-mappings', get_root_folder)) do
      sh("yarn && yarn api-test:ci")
    end
  end

  desc "Run linter for purchases-js-hybrid-mappings"
  lane :lint_js_mappings do |options|
    Dir.chdir(File.expand_path('purchases-js-hybrid-mappings', get_root_folder)) do
      sh("yarn && yarn format:check && yarn lint")
    end
  end

  desc "Deploy purchases-js-hybrid-mappings to npm.js"
  lane :deploy_js_mappings do |options|
    build_and_publish_npm_package("purchases-js-hybrid-mappings")
  end
end

def make_typescript_package_esm
  replace_text_in_files(
    previous_text: "@revenuecat/purchases-typescript-internal",
    new_text: "@revenuecat/purchases-typescript-internal-esm",
    paths_of_files_to_update: ["typescript/package.json"]
  )
  replace_text_in_files(
    previous_text: "commonjs",
    new_text: "esnext",
    paths_of_files_to_update: ["typescript/tsconfig.json"]
  )
end

def build_and_publish_npm_package(folder)
  version_number = current_version_number
  is_prerelease = Gem::Version.new(version_number).prerelease?

  build_args = [
    'yarn && yarn build'
  ]

  publish_args = [
    'npm',
    'publish',
    '--access public',
    is_prerelease ? '--tag next' : nil
  ].compact

  Dir.chdir(File.expand_path(folder, get_root_folder)) do
    sh(build_args)
    sh(publish_args)
  end
end

def current_version_number
  File.read("../.version").strip
end

def check_pods
  pod_lib_lint(
    verbose: true,
    podspec: 'PurchasesHybridCommon.podspec',
    platforms: 'ios,osx,tvos,visionos',
    fail_fast: true
  )
  pod_lib_lint(
    verbose: true,
    podspec: 'PurchasesHybridCommonUI.podspec',
    include_podspecs: 'PurchasesHybridCommon.podspec',
    platforms: 'ios,osx,tvos,visionos',
    fail_fast: true
  )
end

def is_snapshot_version?(version_name)
  version_name.end_with?("-SNAPSHOT")
end

def parse_previous_android_native_version
  parse_version_in_file(/(?<=purchases = ["'])(.*)(?=["'])/, "android/gradle/libs.versions.toml")
end

def parse_previous_ios_native_version
  parse_version_in_file(/(?<=s\.dependency ["']RevenueCat["'], ["'])(.*)(?=["'])/, "PurchasesHybridCommon.podspec")
end

def parse_previous_js_version
  parse_version_in_file(/(?<="@revenuecat\/purchases-js": ["'])(.*)(?=["'])/, "purchases-js-hybrid-mappings/package.json")
end

def parse_version_in_file(pattern, path)
  Dir.chdir(get_root_folder) do
    File.open path do |file|
      line = file.find { |line| line =~ pattern }
      return line.match(pattern)[1] unless line.nil?
    end
  end
  UI.user_error!("Couldn't extract version from #{path}")
end

def get_root_folder
  File.expand_path('../../', __FILE__)
end

def check_no_git_tag_exists(version_number)
  if git_tag_exists(tag: version_number, remote: true, remote_name: 'origin')
    raise "git tag with version #{version_number} already exists!"
  end
end

def detect_bump_type(a, b)
  if a == b
    return :none
  end

  version_a = Gem::Version.new(a)
  version_b = Gem::Version.new(b)

  same_major = version_a.canonical_segments[0] == version_b.canonical_segments[0]
  same_minor = version_a.canonical_segments[1] == version_b.canonical_segments[1]
  if same_major && same_minor
    return :patch
  elsif same_major
    return :minor
  else
    return :major
  end
end

def get_commit_hash_for_tag(repository, tag)
  sh("git ls-remote --tags #{repository} | grep refs/tags/#{tag}^{} | cut -f 1 | tr -d '\n'")
end
