# Uncomment the next line to define a global platform for your project

target 'PurchasesHybridCommon' do
  platform :ios, '11.0'
  use_frameworks!

  pod 'RevenueCat', '4.38.1'

  target 'PurchasesHybridCommonTests' do
    # Pods for testing
    pod 'Quick'
    pod 'Nimble'
  end

  target 'PurchasesHybridCommonIntegrationTests' do
    # Pods for testing
    pod 'Quick'
    pod 'Nimble'
  end

end

target 'PurchasesHybridCommonUI' do
  platform :ios, '11.0'
  use_frameworks!

  pod 'RevenueCat', '4.38.1'
  pod 'RevenueCatUI', '4.38.1'

end

target 'ObjCAPITester' do
  platform :ios, '11.0'
  use_frameworks!

  pod 'RevenueCat', '4.38.1'
  pod 'RevenueCatUI', '4.38.1'
end
