# Uncomment the next line to define a global platform for your project

target 'PurchasesHybridCommon' do
  platform :ios, '9.0'
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PurchasesHybridCommon
  pod 'Purchases', '3.14.1'
  
  target 'PurchasesHybridCommonTests' do
    # Pods for testing
    pod 'Quick'
    pod 'Nimble'
  end

end
