# Uncomment the next line to define a global platform for your project

target 'PurchasesHybridCommon' do
  platform :ios, '11.0'
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PurchasesHybridCommon
  # todo: remove the branch once the feature has been released
  pod 'RevenueCat', :git => 'https://github.com/RevenueCat/purchases-ios.git', :branch => 'feature/expose_signed_data_in_promo_offers'
  
  target 'PurchasesHybridCommonTests' do
    # Pods for testing
    pod 'Quick'
    pod 'Nimble'
  end

end

target 'ObjCAPITester' do
  platform :ios, '11.0'
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PurchasesHybridCommon
  pod 'PurchasesHybridCommon', path: '../../'
  
end
